fix: introduce default 20% deduction from resources.mem_mb and override via params.java_mem_overhead_mv
snakemake/snakemake-wrapper-utils pull request #24
Opened 2023-01-04 16:05 UTC by dlaehnemann

Solves #9 .

An alternative could be to specifiy `-Xmx` (`< resources.mem_mb`) instead of the overhead. I'm not sure which way it's more intuitive (as this whole business of Java memory management is in no way intuitive to me).

2023-01-04 20:54 UTC, johanneskoester requested changes
Good idea! Two things:

1. it should be `resources.java_mem_overhead_mb` instead of `params`. Otherwise, changes would e.g. trigger reruns, although this setting should have no influence on results.
2. Ideally the user should not need to define `java_mem_overhead_mb` at all. It kind of contradicts the idea of wrappers that the user needs to know about this. Instead, it should be possible to specify a default for each wrapper. W can tune these defaults over time. This should be done by introducing a keyword arg: `get_java_opts(snakemake, java_mem_overhead_factor=0.2)`, and use `1.0 - java_mem_overhead_factor` in the calculations below instead of a hardcoded `0.8`.

2023-01-05 11:31 UTC, dlaehnemann commented
Ah, OK. I wasn't aware of this differentiation between `params:` and `resources:`, but it makes a lot of sense. Nice.

And it's true, the overhead can always be specified in relative terms. This also makes sense, if anybody wants to make `mem_mb=` (and then also the overhead fraction) dependent on input size. So the parameter to the `get_java_opts()` function also makes a lot of sense to me.

Thanks for the great suggestions, I'll address then once I'm back at my computer.

2023-01-09 10:42 UTC, dlaehnemann commented
Also, we should do a sweep of all java wrappers, once we have a new release here. This will entail going through tool documentations to see if a higher-than `0.2` JVM memory overhead fraction is required. But anything that's not covered in docs, we'll have to rely on user input for more fine-tuning...

2023-01-09 10:58 UTC, johanneskoester approved these changes

2023-01-09 10:58 UTC, merged